/*
James Plant
B321
ICE_13_1
*/



/*
Create login in master

create and run user in b320
*/


DROP USER B321_S25_APP 
GO


USE MASTER
GO

CREATE LOGIN B321_S25_APP 
WITH PASSWORD = 'Password!'

USE b320
GO

CREATE USER B321_S25_APP 
FOR LOGIN B321_S25_APP
GO



GRANT EXECUTE ON sp_GetAdvisor to B321_S25_APP
GO

GRANT EXECUTE ON sp_InsertAdvisor to B321_S25_APP
GO

GRANT EXECUTE ON sp_UpdateAdvisor to B321_S25_APP
GO

GRANT EXECUTE ON sp_DeleteAdvisor to B321_S25_APP
GO

GRANT EXECUTE ON sp_GetStudent to B321_S25_APP
Go

GRANT EXECUTE ON sp_InsertStudent to B321_S25_APP
Go

GRANT EXECUTE ON sp_UpdateStudent to B321_S25_APP
Go

GRANT EXECUTE ON sp_DeleteStudent to B321_S25_APP
Go

GRANT EXECUTE ON sp_InsertAvailability to B321_S25_APP
Go

GRANT EXECUTE ON sp_UpdateAvailability to B321_S25_APP
Go

GRANT EXECUTE ON sp_DeleteAvailability to B321_S25_APP
Go

GRANT EXECUTE ON sp_GetAvailability to B321_S25_APP
Go

GRANT EXECUTE ON sp_GetAdvisorID to B321_S25_APP
Go

GRANT EXECUTE ON sp_GetMeeting to B321_S25_APP
Go

GRANT EXECUTE ON sp_InsertMeeting to B321_S25_APP
Go

GRANT EXECUTE ON sp_UpdateMeeting to B321_S25_APP
Go

GRANT EXECUTE ON sp_DeleteMeeting to B321_S25_APP
Go

GRANT EXECUTE ON fnGetAdvisorID to B321_S25_APP
Go

GRANT EXECUTE ON fnGetAvailabilityID to B321_S25_APP
Go

GRANT EXECUTE ON fnGetTimeOfAvailability to B321_S25_APP
Go

GRANT EXECUTE ON fnGetAdvisorOfAvailability to B321_S25_APP
Go

GRANT EXECUTE ON fnGetMeetingID to B321_S25_APP
Go

GRANT EXECUTE ON sp_GetTime to B321_S25_APP
Go

GRANT EXECUTE ON sp_InsertTime to B321_S25_APP
Go

GRANT EXECUTE ON sp_UpdateTime to B321_S25_APP
Go

GRANT EXECUTE ON sp_DeleteTime to B321_S25_APP
Go